### ISSUE TITLE
"Back to top", "Skip to content" and Table of Contents do not take in account the top grey bar

### ISSUE THREAD

**Issue by GPhMorin** [wwu-housing/starterbootstrap#17]
The above behaviour results in the page scrolling lower than it should, and most of the time the grey bar hiding the title.

By example, on [this page](http://camlittle.com/dokuwiki/doku.php?id=wiki:syntax), we should be able to see the title when clicking on the [Basic Text Formatting link](http://camlittle.com/dokuwiki/doku.php?id=wiki:syntax#basic_text_formatting) in the Table of Contents, but that title is hidden under the grey top bar.

EDIT : Footnotes are also concerned.

**Comment by voidfy** [comment]
I know this is closed issue but I have question.

How do I change the top margin of section link jump?
