### ISSUE TITLE
<page-break-after:always> does not work on the template.

### ISSUE THREAD

**Issue by voidfy** [wwu-housing/starterbootstrap#59]
Firstly, Thank you so much for this lovely template and I am really pleased about it.

I am trying to use WRAP pagebreak from WRAP plugin.
This code adds div with style of page-break-after:always. So I can break page in print view.
It works on other template. So I assume it's not problem with browser or plugin.

I would really appreciate if you could help me. Thank you so much.

**Comment by apexskier** [comment]
Can you link to the documentation for the plugin you're referring to?

**Comment by voidfy** [comment]
I am not too sure what kind of documentation you are referring to.
The plugin I use is Wrap plugin and the link to download plugin is
https://www.dokuwiki.org/plugin:wrap
The syntax I am trying to use is
<WRAP pagebreak></WRAP>

I hope this is the documentation you need.

**Comment by apexskier** [comment]
I'm not able to reproduce this issue. I've installed the plugin on my test dokuwiki install and get no page break when viewing in chromium, and get a page break in the print preview. Is this how it's supposed to behave?

**Comment by voidfy** [comment]
Firstly, I believe page-break-after only works in print preview.
I could not get that page break in Google Chrome. So I posted this issue.

I was searching keep searching for answer and found solution few hours ago.
I added this
'@media print {
  table {float: none !important; }
  div { float: none !important; }
  .page-break { page-break-inside: avoid; page-break-before: always; }
  .dont-print { display: none; }  
}'
in print.css and it worked.
Someone said it's because bootstrap keeps div float to left by default.
After I found the solution, I have also read there's some problem with
page-break-after property with Google Chrome. So I tested on Firefox
and It worked even without the code above.

So my final conclusion is that,
1. It was actually problem with Google Chrome.
2. With that code above, it works with Google Chrome

**Comment by apexskier** [comment]
Okay, if you want to commit the necessary changes and submit a pull request I can merge them into the main repo!

**Comment by voidfy** [comment]
Firstly, I don't have straight vertical shape page.
I don't have sidebar or anything but text.
So declaring none float in print form works for me.
I don't know what would happen to other websites.
So if you think it's necessary to put it in main repo, then you can put it in!
  
I am new to Github so I don't really know how to submit a pull request.
