### ISSUE TITLE
sidebar breaks TOC

### ISSUE THREAD

**Issue by ToeiRei** [wwu-housing/starterbootstrap#60]
Pages show 'sidebar' headlines in TOC instead of headlines of the actual page.

**Comment by apexskier** [comment]
Can I get a screenshot of this behavior?

**Comment by ToeiRei** [comment]
![wrong headings](https://cloud.githubusercontent.com/assets/5990591/5940895/f28077de-a70d-11e4-9ffa-50505a6b4cbd.JPG)

**Comment by apexskier** [comment]
I've just pushed a fix. Reopen if it doesn't work!
