### ISSUE TITLE
JS Error breaking Edit view

### ISSUE THREAD

**Issue by ToeiRei** [wwu-housing/starterbootstrap#61]
Most recent chrome bailing out at script.js, line 52 saying
"Uncaught ReferenceError: dw_page is not defined"

**Comment by apexskier** [comment]
I'm not seeing that error in a couple tests I did. That variable is defined globally by dokuwiki's own javascript, so I'm not sure what the root of the problem is.

What plugins are you using? What exact version of chrome? What is the resulting issue from this error (what's the ui/ux problem)?

**Comment by ToeiRei** [comment]
Chrome Version: 40.0.2214.93m (most recent at the time of writing/reporting)
dokuwiki version; Release 2014-09-29b "Hrun"
Plugins used: default ones + Changes, Moderncontact
Issue: Editor not showing, toolbar missing (see screenshot)

![image](https://cloud.githubusercontent.com/assets/5990591/5941000/8cb90ae6-a70e-11e4-97e7-624c753e2155.png)

**Comment by ToeiRei** [comment]
It seems like I could track it down:
If I enable "Compact CSS and javascript output" some JS gets broken.

**Comment by apexskier** [comment]
I'm still unable to reproduce this, and my dokuwiki install on my university's server seems to be broken so I'm unable to test. I'm highly skeptical that the version of Chrome is breaking things, and a tiny bit skeptical that it's the DokuWiki version.

Can you try disabling/removing your plugins one-by-one to try to identify if one is breaking things?

**Comment by ToeiRei** [comment]
Same thing with no plugins enabled. See my comment from above. It seems like "Compact CSS and javascript output" breaks things here.

**Comment by apexskier** [comment]
Yeah, I tried enabling that option and still didn't get it. I need to get the most recent version of dokuwiki installed in a testable location. That seems like the most likely culprit at this point.

![compress-css-js](https://cloud.githubusercontent.com/assets/329222/5946182/b0d089f2-a6e8-11e4-96c4-2ef7733820c3.png)

**Comment by apexskier** [comment]
Is the error you mentioned when compressing css/js this?

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
```
