### ISSUE TITLE
Print Version

### ISSUE THREAD

**Issue by oerb** [wwu-housing/starterbootstrap#65]
Nice Work. Love that :) - But I often print some of my sides. In the Printview Top is a "skip to Navigation" Button and the line "your are Here ... domain" that should be hidden by bootstrapoption.

**Comment by apexskier** [comment]
Looks like the "skip to nav" button shows up in chrome, but not safari. I'll make sure it's not there. I originally kept the "you are here" text intentionally, but I think I'll remove it at most browsers insert equivalent information into the header of the printed page.
