### ISSUE TITLE
How to display logo.png

### ISSUE THREAD

**Issue by supertino7** [wwu-housing/starterbootstrap#79]
Hi,

I try to find a way to display the logo.png beside the top title.
Is there a missing tag, currently ? 

Thanks all

**Comment by LeDistordu** [comment]
+1 add support for logo with possibility to change it on admin page

**Comment by apexskier** [comment]
I didn't ever comment on this, but this is now supported. See the [README](https://github.com/wwu-housing/starterbootstrap#logo-support)
